import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from '../app/Components/Navbar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: 'linear-gradient(180deg, rgba(12, 80, 66, 0.77) 0%, rgba(3, 18, 15, 0.77) 100%)',
          margin: 0,
          color: 'white', // Optional
        }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
